"""make application_id nullable in payments

Revision ID: 0e9a65822215
Revises: 4f856f30f720
Create Date: 2025-09-23 09:33:00.654192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e9a65822215'
down_revision = '4f856f30f720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('application_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('application_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
