"""add complain and complain_image tables

Revision ID: 2456c255ac82
Revises: 0e9a65822215
Create Date: 2025-09-24 05:27:47.115907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2456c255ac82'
down_revision = '0e9a65822215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'answered', 'closed', name='complain_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complain_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complain_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['complain_id'], ['complains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=mysql.ENUM('room', 'deposit', 'utilities', 'trash', 'maintenance', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('room', 'trash', 'deposit', 'utilities', 'maintenance', name='payment_services'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.Enum('room', 'trash', 'deposit', 'utilities', 'maintenance', name='payment_services'),
               type_=mysql.ENUM('room', 'deposit', 'utilities', 'trash', 'maintenance', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    op.drop_table('complain_images')
    op.drop_table('complains')
    # ### end Alembic commands ###
